
# Curve fitting prediction example

```{r, message=F}
library(htmlTable)
library(broom)
library(pixiedust)
library(dplyr)
library(pander)
library(data.table)
```
<br>

## Show data

```{r, results='asis',echo=T,message=FALSE, warning=FALSE}

## read data 
df <- fread("./sample_data.csv")

## attribute description simple table
meaning <- c("number of campaign", "number of days", "Cumulative sum of campaigns revenue")
attribute <- c("c1/c2/c3","days", "cumsum_revenue") 
table.df = cbind(attribute, meaning)
kable(table.df, format = "markdown", align="c")

## show data
kable(df, format = "markdown", align="c")

```

<br>

## Curve fitting functions


```{r}


## timeseries for all curves
times = seq(0, 60, 0.1)


## CURVE FUNCTIONS 

linear <- function(y) {

    df$cumsum_revenue = y
    lin.lm <- lm(cumsum_revenue ~ days, data = df)
    pred.lin <- predict(lin.lm, list(days=times))
    return(list(lin.lm, pred.lin))
}


logarithmic <- function (y) {
    
    df$cumsum_revenue = y
    log.lm <- lm(cumsum_revenue ~ log(days), data = df)
    pred.log <- predict(log.lm, list(days=times))
    return(list(log.lm, pred.log))
}


exponential <- function (y) {
    
    df$cumsum_revenue = y
    exp.lm <- lm(log(cumsum_revenue) ~ days, data = df)
    pred.exp <- exp(predict(exp.lm, list(days=times)))
    return(list(exp.lm, pred.exp))
}


polynomial_2 <- function (y) {

    df$cumsum_revenue = y
    poly2.lm <- lm(cumsum_revenue ~ poly(days, 2), data = df)
    pred.poly2 <- predict(poly2.lm, list(days=times))
    return(list(poly2.lm, pred.poly2))
}


polynomial_3 <- function (y) {

    df$cumsum_revenue = y
    poly3.lm <- lm(cumsum_revenue ~ poly(days, 3), data = df)
    pred.poly3 <- predict(poly3.lm, list(days=times))
    return(list(poly3.lm, pred.poly3))
}


models = list("linear" = linear, 
              "logarithmic" = logarithmic,
              "exponential" = exponential, 
              "polynomial_2" = polynomial_2, 
              "polynomial_3" = polynomial_3)


```

<br>

## Save curves plot into list

```{r, fig.show='hide' }


## create list for saving plots as object
plots = list()

## create list for assigning models name
name.list = list()


## loop every curve plot and save it as object into list

for (i in seq(models)) {

    # model name
    name = names(models)[i]

    # assign model name into list
    name.list[[i]] = name

    # function of model
    fun.model = models[[name]]

    # assign model coefficients and statistics 
    mod.val = fun.model(df$cumsum_revenue) [[1]]

    # assign prediction values
    pred.val = fun.model(df$cumsum_revenue) [[2]]


    # set the max ylim value
    not.infinite = pred.val[!is.infinite(pred.val)]
    ylim.max = max(not.infinite) + (max(not.infinite) + (-min(not.infinite)))/3

    # set the min ylim value
    not.infinite = pred.val[!is.infinite(pred.val)]
    ylim.min = min(not.infinite)

    # extrapolation plot
    plot(times, pred.val, xaxt='n', type="l", main=paste(name, "curve"), 
         ylab = "Cumulative campaign revenue", xlab="Number of days", 
         cex.lab=1.0, cex.main=1.1, ylim=c(ylim.min, ylim.max),
         xlim=c(0,60), col = '#FF00007F', lwd=4) 

    # add grid
    grid(NA, NULL)

    # add points from original data
    points(df$days, df$cumsum_revenue, col="#0000FF7F", pch = 16, cex = 1.4)

    # modificate the plot axis
    axis(1, at=seq(0,60,10), labels=seq(0,60,10))

    # add legend to a plot
    legend("top",  
           legend=c(paste("Estimation by", name, "function"), "Campaign revenue", 
           as.expression(bquote(
           R^2==.(format(summary(mod.val)$r.squared, digits=3))))),
           pch=c(NA,16),col=c("#FF00007F", "#0000FF7F"), 
           lwd = 4, lty=c(1,0,0), cex = 0.7, pt.cex = 1.2, 
           merge = T, y.intersp=2.0)

    # save every plot into list 'plots'
    plots[[i]] = recordPlot()

}   


## assign model names into plots list
names(plots) = unlist(name.list)



```
<br>


## Linear model

```{r, fig.height = 5, fig.width=7, fig.align='center', dpi = 300}

plots[["linear"]]

```

<br>

## Logarithmic model


```{r, fig.height = 5, fig.width=7, fig.align='center', dpi = 300}

plots[["logarithmic"]]

```

<br>

## Exponential model


```{r, fig.height = 5, fig.width=7, fig.align='center', dpi = 300}

plots[["exponential"]]

```

<br>

## Polynomial (quadratic)

```{r, fig.height = 5, fig.width=7, fig.align='center', dpi = 300}

plots[["polynomial_2"]]

```

<br>

## Polynomial (cubic)

```{r, fig.height = 5, fig.width=7, fig.align='center', dpi = 300}

plots[["polynomial_3"]]

```

```{r, echo=F, eval=F}

## table of statistics
stats = round(glance(lin.lm), 3)
htmlTable(stats)


## table of coefficients
coeff = as.data.frame(dust(lin.lm) %>% sprinkle(round = 3))
htmlTable(coeff)

```

<br>

## Sorted table by R squared value

```{r, results='asis',echo=T,warning=F}

## lists for collecting stats with r.squared value
model.stats = list()
model.r.squared = list()


## loop for creating table with r squared values and models name 

for (i in seq(models)) {
    fun.model = models[[ name.list[[i]] ]]
    model.stats[[i]] = glance( fun.model(df$cumsum_revenue) [[1]] )        
    model.r.squared[[i]]  = round(model.stats[[i]]$r.squared, 3)
    results = data.table(cbind(Funtion = unlist(name.list), 
                            R.squared = unlist(model.r.squared)))
}

## sort results data.table by R.squared values
r.squared.table = results[ order(-R.squared) ]

## show r.squared.table 
kable(r.squared.table, align='c', format='markdown', row.names=T)


```

<br>

## Fit campaigns to the best function


```{r, results='asis', fig.height = 5, fig.width=7, fig.align='center', dpi = 300}

## select campaigns from data
campaigns = df[, grep("c[0-9]", names(df)), with = F]

## best function index
best.index = which.max(results$R.squared)

## best function 
best.fun = models[[best.index]]


## campaigns curve fitting by best function

for (i in seq(campaigns)) {

    # assign single campaign into camp
    camp = campaigns[[i]]

    # campaign name
    name = names(campaigns)[i]

    # assign model coefficients and statistics 
    mod.val = best.fun(camp) [[1]]

    # assign prediction values
    pred.val = best.fun(camp) [[2]]

    # set the max ylim value
    not.infinite = pred.val[!is.infinite(pred.val)]
    ylim.max = max(not.infinite) + (max(not.infinite) + (-min(not.infinite)))/3

    # set the min ylim value
    not.infinite = pred.val[!is.infinite(pred.val)]
    ylim.min = min(not.infinite)

    # increase space between plots
    cat("<br/> <br/> <br/>")

    # predicted revenue head-line 
    pred = round(max(pred.val), 2)
    head = paste('Predicted revenue for campaign', name, "on 60th day is",
                pred, "€")
    pandoc.header(head, 4)
    pandoc.horizontal.rule()
    pandoc.horizontal.rule()

    
    # extrapolation plot
    plot(times, pred.val, xaxt='n', type="l", main=paste("Campaign", name), 
         ylab = "Predicted campaign revenue", xlab="Number of days", 
         cex.lab=1.0, cex.main=1.1, ylim=c(ylim.min, ylim.max),
         xlim=c(0,60), col = '#FF00007F', lwd=4) 

    # add grid
    grid(NA, NULL)

    # add points from original data
    points(df$days, camp, col="#0000FF7F", pch = 16, cex = 1.4)

    # modificate the plot axis
    axis(1, at=seq(0,60,10), labels=seq(0,60,10))

    # add legend to a plot
    legend("top", 
           legend=c(paste("Estimation by",  name.list[[best.index]],"function"),
                    "Campaign revenue", 
           as.expression(bquote(
           R^2==.(format(summary(mod.val)$r.squared, digits=3))))),
           pch=c(NA,16),col=c("#FF00007F", "#0000FF7F"), 
           lwd = 4, lty=c(1,0,0), cex = 0.7, pt.cex = 1.2, 
           merge = T, y.intersp=1.2)
}   

```

